app:
  settings:
    records-per-page-count: 100

spring:
  liquibase:
    user: postgres
    password: mysecretpassword
    change-log: /liquibase/changelog.xml
    url: "jdbc:postgresql://localhost:5432/postgres"
    database-change-log-table: contacts_databaseChangeLog
    database-change-log-lock-table: contacts_databaseChangeLogLock
    liquibase-schema: public
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: DEBUG